### ISSUE TITLE
The ngrok agent (v3) only accepts long name flags prefixed with -- and will error if a single hyphen is used

### ISSUE THREAD

**Issue by MiguelArgentina** [texpert/ngrok-wrapper#20]
I came by your wonderful wrapper and realized that because of the latest [ngrok service update](https://ngrok.com/docs/guides/upgrade-v2-v3#upgrading-command-line-scripts), I couldn't connect to the it.
I got it working adding a hyphen to the lines there one hyphen was used to send flags to the service (most of the where the -log flag is sent and also in the `ngrok_exec_params` method.
I didn't create a PR with these changes because I don't know how to handle older and newer versions of it (if older versions are still being used)

**Comment by texpert** [comment]
@MiguelArgentina, thanks for kind appreciation!

Ngrok v3 support just landed in the new release - https://github.com/texpert/ngrok-wrapper/releases/tag/v0.3.0
