### ISSUE TITLE
Config error with Ngrok v3.3.3

### ISSUE THREAD

**Issue by Circuit8** [texpert/ngrok-wrapper#31]
Hi there. This library was working great for me, but I've just upgraded my Ubuntu installation and had to reinstall ngrok and it seems to not be working with the latest version, I get the following error:

```
ERROR:  Error reading configuration file '/dev/null': `version` property is required.
ERROR:  
ERROR:  If you're upgrading from an older version of ngrok, you can run:
ERROR:  
ERROR:      ngrok config upgrade
ERROR:  
ERROR:  to upgrade to the new format and add the version number.
```

Thanks for your help.

**Comment by texpert** [comment]
Hi, @Circuit8!

The error is explicitly telling to add the version number to your `ngrok` config file.

"It adds a version field which is now required and identifies the configuration version to use. The latest is version: 2", as you can read here - https://ngrok.com/docs/guides/upgrade-v2-v3/#upgrading-the-ngrok-agent-config

Mine, is, for example, like this:

```
21:34 $ ngrok --version
ngrok version 3.3.2

# /Users/aurel/.ngrok2/ngrok.yml

authtoken: the_ngrok_token
region: eu
version: "2"

```

Can you try this?

**Comment by Circuit8** [comment]
Thanks for your response. So I added that to my ngrok config file, but continued to get the same error. I changed my `Ngrok::Wrapper.start` call to pass in the config yml file path, and now it does not error, but `Ngrok::Wrapper.ngrok_url` returns `nil`.

**Comment by texpert** [comment]
What is `Ngrok::Wrapper.ngrok_url_https` returning?

You can have a look at my sample application using the `ngrok-wrapper` - https://github.com/texpert/rails_6_rss_reader/blob/main/config/environments/development.rb

**Comment by Circuit8** [comment]
Ah yep that's working again now thanks alot! Needed to use `Ngrok::Wrapper.ngrok_url_https` instead of `Ngrok::Wrapper.ngrok_url`
